/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_glumes_cppso_aviplayer_AviPlayer */

#ifndef _Included_com_glumes_cppso_aviplayer_AviPlayer
#define _Included_com_glumes_cppso_aviplayer_AviPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_glumes_cppso_aviplayer_AviPlayer
 * Method:    open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_glumes_cppso_aviplayer_AviPlayer_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_glumes_cppso_aviplayer_AviPlayer
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_glumes_cppso_aviplayer_AviPlayer_getWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_glumes_cppso_aviplayer_AviPlayer
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_glumes_cppso_aviplayer_AviPlayer_getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_glumes_cppso_aviplayer_AviPlayer
 * Method:    getFrameRate
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_glumes_cppso_aviplayer_AviPlayer_getFrameRate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_glumes_cppso_aviplayer_AviPlayer
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_glumes_cppso_aviplayer_AviPlayer_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_glumes_cppso_aviplayer_AviPlayer
 * Method:    render
 * Signature: (JLandroid/graphics/Bitmap;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_glumes_cppso_aviplayer_AviPlayer_render
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
