/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_glumes_cppso_jnioperations_ThreadOps */

#ifndef _Included_com_glumes_cppso_jnioperations_ThreadOps
#define _Included_com_glumes_cppso_jnioperations_ThreadOps
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_glumes_cppso_jnioperations_ThreadOps
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_glumes_cppso_jnioperations_ThreadOps_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_glumes_cppso_jnioperations_ThreadOps
 * Method:    nativeFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_glumes_cppso_jnioperations_ThreadOps_nativeFree
  (JNIEnv *, jobject);

/*
 * Class:     com_glumes_cppso_jnioperations_ThreadOps
 * Method:    nativeWorker
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_glumes_cppso_jnioperations_ThreadOps_nativeWorker
  (JNIEnv *, jobject);

/*
 * Class:     com_glumes_cppso_jnioperations_ThreadOps
 * Method:    posixThreads
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_glumes_cppso_jnioperations_ThreadOps_posixThreads
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
