/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_glumes_cppso_jnioperations_BitmapOps */

#ifndef _Included_com_glumes_cppso_jnioperations_BitmapOps
#define _Included_com_glumes_cppso_jnioperations_BitmapOps
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_glumes_cppso_jnioperations_BitmapOps
 * Method:    rotateBitmap
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_glumes_cppso_jnioperations_BitmapOps_rotateBitmap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_glumes_cppso_jnioperations_BitmapOps
 * Method:    convertBitmap
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_glumes_cppso_jnioperations_BitmapOps_convertBitmap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_glumes_cppso_jnioperations_BitmapOps
 * Method:    mirrorBitmap
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_glumes_cppso_jnioperations_BitmapOps_mirrorBitmap
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
